//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dipllom.DataFileApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class newShamilEntities : DbContext
    {
        public newShamilEntities()
            : base("name=newShamilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Prod> Prod { get; set; }
        public virtual DbSet<Prod2> Prod2 { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudniki { get; set; }
        public virtual DbSet<Special> Special { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Type2> Type2 { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Usluga> Usluga { get; set; }
        public virtual DbSet<Zakazi> Zakazi { get; set; }
        public virtual DbSet<Realiz> Realiz { get; set; }
    }
}
