//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dipllom.DataFileApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prod2
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Tipe { get; set; }
        public int Price { get; set; }
        public string Kolich { get; set; }
        public int Itogo { get; set; }
    }
}
