//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dipllom.DataFileApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zakazi
    {
        public int Id { get; set; }
        public int IdUsluga { get; set; }
        public int IdSotrudniki { get; set; }
        public string Data { get; set; }
        public string Zakazchik { get; set; }
    
        public virtual Sotrudniki Sotrudniki { get; set; }
        public virtual Usluga Usluga { get; set; }
    }
}
